// <copyright file="PaypalServerSdkClient.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using APIMatic.Core.Utilities.Logger.Configuration;
using Microsoft.Extensions.Configuration;
using PaypalServerSdk.Standard.Apis;
using PaypalServerSdk.Standard.Authentication;
using PaypalServerSdk.Standard.Http.Client;
using PaypalServerSdk.Standard.Logging;
using System;
using System.Collections.Generic;

namespace PaypalServerSdk.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Api and holds the
    /// configuration of the SDK.
    /// </summary>
    public sealed class PaypalServerSdkClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Sandbox, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://api-m.sandbox.paypal.com" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private SdkLoggingConfiguration sdkLoggingConfiguration;
        private const string userAgent = "PayPal REST API DotNet SDK, Version: 1.1.1, on OS {os-info}";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<OrdersApi> orders;
        private readonly Lazy<PaymentsApi> payments;
        private readonly Lazy<VaultApi> vault;
        private readonly Lazy<TransactionSearchApi> transactionSearch;
        private readonly Lazy<SubscriptionsApi> subscriptions;
        private readonly Lazy<OAuthAuthorizationApi> oAuthAuthorization;

        private PaypalServerSdkClient(
            Environment environment,
            ClientCredentialsAuthModel clientCredentialsAuthModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration,
            SdkLoggingConfiguration sdkLoggingConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            this.sdkLoggingConfiguration = sdkLoggingConfiguration;
            ClientCredentialsAuthModel = clientCredentialsAuthModel;
            var clientCredentialsAuthManager = new ClientCredentialsAuthManager(clientCredentialsAuthModel,
                () => OAuthAuthorizationApi);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"Oauth2", clientCredentialsAuthManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Default)
                .LoggingConfig(sdkLoggingConfiguration)
                .UserAgent(userAgent)
                .Build();
            ClientCredentialsAuth = clientCredentialsAuthManager;

            this.orders = new Lazy<OrdersApi>(
                () => new OrdersApi(globalConfiguration));
            this.payments = new Lazy<PaymentsApi>(
                () => new PaymentsApi(globalConfiguration));
            this.vault = new Lazy<VaultApi>(
                () => new VaultApi(globalConfiguration));
            this.transactionSearch = new Lazy<TransactionSearchApi>(
                () => new TransactionSearchApi(globalConfiguration));
            this.subscriptions = new Lazy<SubscriptionsApi>(
                () => new SubscriptionsApi(globalConfiguration));
            this.oAuthAuthorization = new Lazy<OAuthAuthorizationApi>(
                () => new OAuthAuthorizationApi(globalConfiguration));
        }

        /// <summary>
        /// Gets OrdersApi.
        /// </summary>
        public OrdersApi OrdersApi => this.orders.Value;

        /// <summary>
        /// Gets PaymentsApi.
        /// </summary>
        public PaymentsApi PaymentsApi => this.payments.Value;

        /// <summary>
        /// Gets VaultApi.
        /// </summary>
        public VaultApi VaultApi => this.vault.Value;

        /// <summary>
        /// Gets TransactionSearchApi.
        /// </summary>
        public TransactionSearchApi TransactionSearchApi => this.transactionSearch.Value;

        /// <summary>
        /// Gets SubscriptionsApi.
        /// </summary>
        public SubscriptionsApi SubscriptionsApi => this.subscriptions.Value;

        /// <summary>
        /// Gets OAuthAuthorizationApi.
        /// </summary>
        public OAuthAuthorizationApi OAuthAuthorizationApi => this.oAuthAuthorization.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with ClientCredentialsAuth.
        /// </summary>
        public IClientCredentialsAuth ClientCredentialsAuth { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with ClientCredentialsAuth.
        /// </summary>
        public ClientCredentialsAuthModel ClientCredentialsAuthModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Default)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the PaypalServerSdkClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .LoggingConfig(sdkLoggingConfiguration)
                .HttpClientConfig(config => config.Build());

            if (ClientCredentialsAuthModel != null)
            {
                builder.ClientCredentialsAuth(ClientCredentialsAuthModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> PaypalServerSdkClient.</returns>
        internal static PaypalServerSdkClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("PAYPAL_SERVER_SDK_STANDARD_ENVIRONMENT");
            string oAuthClientId = System.Environment.GetEnvironmentVariable("PAYPAL_SERVER_SDK_STANDARD_O_AUTH_CLIENT_ID");
            string oAuthClientSecret = System.Environment.GetEnvironmentVariable("PAYPAL_SERVER_SDK_STANDARD_O_AUTH_CLIENT_SECRET");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (oAuthClientId != null && oAuthClientSecret != null)
            {
                builder.ClientCredentialsAuth(new ClientCredentialsAuthModel
                .Builder(oAuthClientId, oAuthClientSecret)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> PaypalServerSdkClient.</returns>
        public static PaypalServerSdkClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = PaypalServerSdk.Standard.Environment.Sandbox;
            private ClientCredentialsAuthModel _clientCredentialsAuthModel = new ClientCredentialsAuthModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;
            private SdkLoggingConfiguration _sdkLoggingConfiguration;

            /// <summary>
            /// Sets credentials for ClientCredentialsAuth.
            /// </summary>
            /// <param name="clientCredentialsAuthModel">ClientCredentialsAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder ClientCredentialsAuth(ClientCredentialsAuthModel clientCredentialsAuthModel)
            {
                _clientCredentialsAuthModel = clientCredentialsAuthModel ??
                    throw new ArgumentNullException(nameof(clientCredentialsAuthModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the default logging configuration, using the Console logger.
            /// </summary>
            /// <returns>Builder.</returns>
            public Builder LoggingConfig()
            {
                _sdkLoggingConfiguration = SdkLoggingConfiguration.Console();
                return this;
            }

            /// <summary>
            /// Sets the logging configuration using the provided <paramref name="action"/>.
            /// </summary>
            /// <param name="action">The action to perform on the logging configuration builder.</param>
            /// <returns>Builder.</returns>
            /// <exception cref="ArgumentNullException">Thrown when <paramref name="action"/> is null.</exception>
            public Builder LoggingConfig(Action<LogBuilder> action)
            {
                if (action is null) throw new ArgumentNullException(nameof(action));
                var logBuilder =
                    LogBuilder.CreateFromConfig(_sdkLoggingConfiguration ?? SdkLoggingConfiguration.Console());
                action(logBuilder);
                _sdkLoggingConfiguration = logBuilder.Build();
                return this;
            }

            internal Builder LoggingConfig(SdkLoggingConfiguration configuration)
            {
                _sdkLoggingConfiguration = configuration;
                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the PaypalServerSdkClient using the values provided for the builder.
            /// </summary>
            /// <returns>PaypalServerSdkClient.</returns>
            public PaypalServerSdkClient Build()
            {
                if (_clientCredentialsAuthModel.OAuthClientId == null || _clientCredentialsAuthModel.OAuthClientSecret == null)
                {
                    _clientCredentialsAuthModel = null;
                }
                return new PaypalServerSdkClient(
                    _environment,
                    _clientCredentialsAuthModel,
                    _httpCallback,
                    _httpClientConfig.Build(),
                    _sdkLoggingConfiguration);
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<PaypalServerSdkClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.ClientCredentialsAuth != null)
                    builder.ClientCredentialsAuth(ClientCredentialsAuthModel.FromOptions(options.ClientCredentialsAuth));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                if (options.LoggingConfig != null)
                    builder.LoggingConfig(LogBuilder.FromOptions(options.LoggingConfig));
                return builder;
            }
        }

        public class PaypalServerSdkClientOptions
        {
            public Environment? Environment { get; set; }
            public ClientCredentialsAuthModelOptions ClientCredentialsAuth { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
            public LoggingConfigOptions LoggingConfig { get; set; }
        }
    }
}
