// <copyright file="ApplePayDecryptedTokenData.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// ApplePayDecryptedTokenData.
    /// </summary>
    public class ApplePayDecryptedTokenData
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApplePayDecryptedTokenData"/> class.
        /// </summary>
        public ApplePayDecryptedTokenData()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ApplePayDecryptedTokenData"/> class.
        /// </summary>
        /// <param name="tokenizedCard">tokenized_card.</param>
        /// <param name="transactionAmount">transaction_amount.</param>
        /// <param name="deviceManufacturerId">device_manufacturer_id.</param>
        /// <param name="paymentDataType">payment_data_type.</param>
        /// <param name="paymentData">payment_data.</param>
        public ApplePayDecryptedTokenData(
            Models.ApplePayTokenizedCard tokenizedCard,
            Models.Money transactionAmount = null,
            string deviceManufacturerId = null,
            Models.ApplePayPaymentDataType? paymentDataType = null,
            Models.ApplePayPaymentData paymentData = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.TransactionAmount = transactionAmount;
            this.TokenizedCard = tokenizedCard;
            this.DeviceManufacturerId = deviceManufacturerId;
            this.PaymentDataType = paymentDataType;
            this.PaymentData = paymentData;
        }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("transaction_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money TransactionAmount { get; set; }

        /// <summary>
        /// The payment card to use to fund a payment. Can be a credit or debit card.
        /// </summary>
        [JsonProperty("tokenized_card")]
        public Models.ApplePayTokenizedCard TokenizedCard { get; set; }

        /// <summary>
        /// Apple Pay Hex-encoded device manufacturer identifier. The pattern is defined by an external party and supports Unicode.
        /// </summary>
        [JsonProperty("device_manufacturer_id", NullValueHandling = NullValueHandling.Ignore)]
        public string DeviceManufacturerId { get; set; }

        /// <summary>
        /// Indicates the type of payment data passed, in case of Non China the payment data is 3DSECURE and for China it is EMV.
        /// </summary>
        [JsonProperty("payment_data_type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ApplePayPaymentDataType? PaymentDataType { get; set; }

        /// <summary>
        /// Information about the decrypted apple pay payment data for the token like cryptogram, eci indicator.
        /// </summary>
        [JsonProperty("payment_data", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ApplePayPaymentData PaymentData { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ApplePayDecryptedTokenData : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TransactionAmount = {(this.TransactionAmount == null ? "null" : this.TransactionAmount.ToString())}");
            toStringOutput.Add($"TokenizedCard = {(this.TokenizedCard == null ? "null" : this.TokenizedCard.ToString())}");
            toStringOutput.Add($"DeviceManufacturerId = {this.DeviceManufacturerId ?? "null"}");
            toStringOutput.Add($"PaymentDataType = {(this.PaymentDataType == null ? "null" : this.PaymentDataType.ToString())}");
            toStringOutput.Add($"PaymentData = {(this.PaymentData == null ? "null" : this.PaymentData.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}