// <copyright file="AuthenticationResponse.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// AuthenticationResponse.
    /// </summary>
    public class AuthenticationResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationResponse"/> class.
        /// </summary>
        public AuthenticationResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticationResponse"/> class.
        /// </summary>
        /// <param name="liabilityShift">liability_shift.</param>
        /// <param name="threeDSecure">three_d_secure.</param>
        public AuthenticationResponse(
            Models.LiabilityShiftIndicator? liabilityShift = null,
            Models.ThreeDSecureAuthenticationResponse threeDSecure = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.LiabilityShift = liabilityShift;
            this.ThreeDSecure = threeDSecure;
        }

        /// <summary>
        /// Liability shift indicator. The outcome of the issuer's authentication.
        /// </summary>
        [JsonProperty("liability_shift", NullValueHandling = NullValueHandling.Ignore)]
        public Models.LiabilityShiftIndicator? LiabilityShift { get; set; }

        /// <summary>
        /// Results of 3D Secure Authentication.
        /// </summary>
        [JsonProperty("three_d_secure", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ThreeDSecureAuthenticationResponse ThreeDSecure { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AuthenticationResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"LiabilityShift = {(this.LiabilityShift == null ? "null" : this.LiabilityShift.ToString())}");
            toStringOutput.Add($"ThreeDSecure = {(this.ThreeDSecure == null ? "null" : this.ThreeDSecure.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}