// <copyright file="BalanceInformation.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// BalanceInformation.
    /// </summary>
    public class BalanceInformation
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BalanceInformation"/> class.
        /// </summary>
        public BalanceInformation()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BalanceInformation"/> class.
        /// </summary>
        /// <param name="currency">currency.</param>
        /// <param name="totalBalance">total_balance.</param>
        /// <param name="primary">primary.</param>
        /// <param name="availableBalance">available_balance.</param>
        /// <param name="withheldBalance">withheld_balance.</param>
        public BalanceInformation(
            string currency,
            Models.Money totalBalance,
            bool? primary = null,
            Models.Money availableBalance = null,
            Models.Money withheldBalance = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Currency = currency;
            this.Primary = primary;
            this.TotalBalance = totalBalance;
            this.AvailableBalance = availableBalance;
            this.WithheldBalance = withheldBalance;
        }

        /// <summary>
        /// The [three-character ISO-4217 currency code](/docs/integration/direct/rest/currency-codes/) that identifies the currency.
        /// </summary>
        [JsonProperty("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Optional field representing if the currency is primary currency or not.
        /// </summary>
        [JsonProperty("primary", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Primary { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("total_balance")]
        public Models.Money TotalBalance { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("available_balance", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money AvailableBalance { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("withheld_balance", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money WithheldBalance { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"BalanceInformation : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Currency = {this.Currency ?? "null"}");
            toStringOutput.Add($"Primary = {(this.Primary == null ? "null" : this.Primary.ToString())}");
            toStringOutput.Add($"TotalBalance = {(this.TotalBalance == null ? "null" : this.TotalBalance.ToString())}");
            toStringOutput.Add($"AvailableBalance = {(this.AvailableBalance == null ? "null" : this.AvailableBalance.ToString())}");
            toStringOutput.Add($"WithheldBalance = {(this.WithheldBalance == null ? "null" : this.WithheldBalance.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}