// <copyright file="CartInformation.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// CartInformation.
    /// </summary>
    public class CartInformation
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CartInformation"/> class.
        /// </summary>
        public CartInformation()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CartInformation"/> class.
        /// </summary>
        /// <param name="itemDetails">item_details.</param>
        /// <param name="taxInclusive">tax_inclusive.</param>
        /// <param name="paypalInvoiceId">paypal_invoice_id.</param>
        public CartInformation(
            List<Models.ItemDetails> itemDetails = null,
            bool? taxInclusive = false,
            string paypalInvoiceId = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ItemDetails = itemDetails;
            this.TaxInclusive = taxInclusive;
            this.PaypalInvoiceId = paypalInvoiceId;
        }

        /// <summary>
        /// An array of item details.
        /// </summary>
        [JsonProperty("item_details", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ItemDetails> ItemDetails { get; set; }

        /// <summary>
        /// Indicates whether the item amount or the shipping amount already includes tax.
        /// </summary>
        [JsonProperty("tax_inclusive", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TaxInclusive { get; set; }

        /// <summary>
        /// The ID of the invoice. Appears for only PayPal-generated invoices.
        /// </summary>
        [JsonProperty("paypal_invoice_id", NullValueHandling = NullValueHandling.Ignore)]
        public string PaypalInvoiceId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"CartInformation : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ItemDetails = {(this.ItemDetails == null ? "null" : $"[{string.Join(", ", this.ItemDetails)} ]")}");
            toStringOutput.Add($"TaxInclusive = {(this.TaxInclusive == null ? "null" : this.TaxInclusive.ToString())}");
            toStringOutput.Add($"PaypalInvoiceId = {this.PaypalInvoiceId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}