// <copyright file="ModifySubscriptionRequest.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// ModifySubscriptionRequest.
    /// </summary>
    public class ModifySubscriptionRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModifySubscriptionRequest"/> class.
        /// </summary>
        public ModifySubscriptionRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ModifySubscriptionRequest"/> class.
        /// </summary>
        /// <param name="planId">plan_id.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="shippingAmount">shipping_amount.</param>
        /// <param name="shippingAddress">shipping_address.</param>
        /// <param name="applicationContext">application_context.</param>
        /// <param name="plan">plan.</param>
        public ModifySubscriptionRequest(
            string planId = null,
            string quantity = null,
            Models.Money shippingAmount = null,
            Models.ShippingDetails shippingAddress = null,
            Models.SubscriptionPatchApplicationContext applicationContext = null,
            Models.PlanOverride plan = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.PlanId = planId;
            this.Quantity = quantity;
            this.ShippingAmount = shippingAmount;
            this.ShippingAddress = shippingAddress;
            this.ApplicationContext = applicationContext;
            this.Plan = plan;
        }

        /// <summary>
        /// The unique PayPal-generated ID for the plan.
        /// </summary>
        [JsonProperty("plan_id", NullValueHandling = NullValueHandling.Ignore)]
        public string PlanId { get; set; }

        /// <summary>
        /// The quantity of the product or service in the subscription.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Ignore)]
        public string Quantity { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("shipping_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money ShippingAmount { get; set; }

        /// <summary>
        /// The shipping details.
        /// </summary>
        [JsonProperty("shipping_address", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ShippingDetails ShippingAddress { get; set; }

        /// <summary>
        /// The application context, which customizes the payer experience during the subscription approval process with PayPal.
        /// </summary>
        [JsonProperty("application_context", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SubscriptionPatchApplicationContext ApplicationContext { get; set; }

        /// <summary>
        /// An inline plan object to customise the subscription. You can override plan level default attributes by providing customised values for the subscription in this object.
        /// </summary>
        [JsonProperty("plan", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PlanOverride Plan { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ModifySubscriptionRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PlanId = {this.PlanId ?? "null"}");
            toStringOutput.Add($"Quantity = {this.Quantity ?? "null"}");
            toStringOutput.Add($"ShippingAmount = {(this.ShippingAmount == null ? "null" : this.ShippingAmount.ToString())}");
            toStringOutput.Add($"ShippingAddress = {(this.ShippingAddress == null ? "null" : this.ShippingAddress.ToString())}");
            toStringOutput.Add($"ApplicationContext = {(this.ApplicationContext == null ? "null" : this.ApplicationContext.ToString())}");
            toStringOutput.Add($"Plan = {(this.Plan == null ? "null" : this.Plan.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}