// <copyright file="OrderTrackerRequest.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// OrderTrackerRequest.
    /// </summary>
    public class OrderTrackerRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderTrackerRequest"/> class.
        /// </summary>
        public OrderTrackerRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OrderTrackerRequest"/> class.
        /// </summary>
        /// <param name="captureId">capture_id.</param>
        /// <param name="trackingNumber">tracking_number.</param>
        /// <param name="carrier">carrier.</param>
        /// <param name="carrierNameOther">carrier_name_other.</param>
        /// <param name="notifyPayer">notify_payer.</param>
        /// <param name="items">items.</param>
        public OrderTrackerRequest(
            string captureId,
            string trackingNumber = null,
            Models.ShipmentCarrier? carrier = null,
            string carrierNameOther = null,
            bool? notifyPayer = false,
            List<Models.OrderTrackerItem> items = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.TrackingNumber = trackingNumber;
            this.Carrier = carrier;
            this.CarrierNameOther = carrierNameOther;
            this.CaptureId = captureId;
            this.NotifyPayer = notifyPayer;
            this.Items = items;
        }

        /// <summary>
        /// The tracking number for the shipment. This property supports Unicode.
        /// </summary>
        [JsonProperty("tracking_number", NullValueHandling = NullValueHandling.Ignore)]
        public string TrackingNumber { get; set; }

        /// <summary>
        /// The carrier for the shipment. Some carriers have a global version as well as local subsidiaries. The subsidiaries are repeated over many countries and might also have an entry in the global list. Choose the carrier for your country. If the carrier is not available for your country, choose the global version of the carrier. If your carrier name is not in the list, set `carrier` to `OTHER` and set carrier name in `carrier_name_other`. For allowed values, see Carriers.
        /// </summary>
        [JsonProperty("carrier", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ShipmentCarrier? Carrier { get; set; }

        /// <summary>
        /// The name of the carrier for the shipment. Provide this value only if the carrier parameter is OTHER. This property supports Unicode.
        /// </summary>
        [JsonProperty("carrier_name_other", NullValueHandling = NullValueHandling.Ignore)]
        public string CarrierNameOther { get; set; }

        /// <summary>
        /// The PayPal capture ID.
        /// </summary>
        [JsonProperty("capture_id")]
        public string CaptureId { get; set; }

        /// <summary>
        /// If true, PayPal will send an email notification to the payer of the PayPal transaction. The email contains the tracking details provided through the Orders tracking API request. Independent of any value passed for `notify_payer`, the payer may receive tracking notifications within the PayPal app, based on the user's notification preferences.
        /// </summary>
        [JsonProperty("notify_payer", NullValueHandling = NullValueHandling.Ignore)]
        public bool? NotifyPayer { get; set; }

        /// <summary>
        /// An array of details of items in the shipment.
        /// </summary>
        [JsonProperty("items", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.OrderTrackerItem> Items { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"OrderTrackerRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"TrackingNumber = {this.TrackingNumber ?? "null"}");
            toStringOutput.Add($"Carrier = {(this.Carrier == null ? "null" : this.Carrier.ToString())}");
            toStringOutput.Add($"CarrierNameOther = {this.CarrierNameOther ?? "null"}");
            toStringOutput.Add($"CaptureId = {this.CaptureId ?? "null"}");
            toStringOutput.Add($"NotifyPayer = {(this.NotifyPayer == null ? "null" : this.NotifyPayer.ToString())}");
            toStringOutput.Add($"Items = {(this.Items == null ? "null" : $"[{string.Join(", ", this.Items)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}