// <copyright file="PaymentPreferences.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// PaymentPreferences.
    /// </summary>
    public class PaymentPreferences
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentPreferences"/> class.
        /// </summary>
        public PaymentPreferences()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentPreferences"/> class.
        /// </summary>
        /// <param name="autoBillOutstanding">auto_bill_outstanding.</param>
        /// <param name="setupFee">setup_fee.</param>
        /// <param name="setupFeeFailureAction">setup_fee_failure_action.</param>
        /// <param name="paymentFailureThreshold">payment_failure_threshold.</param>
        public PaymentPreferences(
            bool? autoBillOutstanding = true,
            Models.Money setupFee = null,
            Models.SetupFeeFailureAction? setupFeeFailureAction = Models.SetupFeeFailureAction.Cancel,
            int? paymentFailureThreshold = 0)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AutoBillOutstanding = autoBillOutstanding;
            this.SetupFee = setupFee;
            this.SetupFeeFailureAction = setupFeeFailureAction;
            this.PaymentFailureThreshold = paymentFailureThreshold;
        }

        /// <summary>
        /// Indicates whether to automatically bill the outstanding amount in the next billing cycle.
        /// </summary>
        [JsonProperty("auto_bill_outstanding", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AutoBillOutstanding { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("setup_fee", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money SetupFee { get; set; }

        /// <summary>
        /// The action to take on the subscription if the initial payment for the setup fails.
        /// </summary>
        [JsonProperty("setup_fee_failure_action", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SetupFeeFailureAction? SetupFeeFailureAction { get; set; }

        /// <summary>
        /// The maximum number of payment failures before a subscription is suspended. For example, if `payment_failure_threshold` is `2`, the subscription automatically updates to the `SUSPEND` state if two consecutive payments fail.
        /// </summary>
        [JsonProperty("payment_failure_threshold", NullValueHandling = NullValueHandling.Ignore)]
        public int? PaymentFailureThreshold { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaymentPreferences : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AutoBillOutstanding = {(this.AutoBillOutstanding == null ? "null" : this.AutoBillOutstanding.ToString())}");
            toStringOutput.Add($"SetupFee = {(this.SetupFee == null ? "null" : this.SetupFee.ToString())}");
            toStringOutput.Add($"SetupFeeFailureAction = {(this.SetupFeeFailureAction == null ? "null" : this.SetupFeeFailureAction.ToString())}");
            toStringOutput.Add($"PaymentFailureThreshold = {(this.PaymentFailureThreshold == null ? "null" : this.PaymentFailureThreshold.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}