// <copyright file="PaypalWalletExperienceContext.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// PaypalWalletExperienceContext.
    /// </summary>
    public class PaypalWalletExperienceContext
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaypalWalletExperienceContext"/> class.
        /// </summary>
        public PaypalWalletExperienceContext()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaypalWalletExperienceContext"/> class.
        /// </summary>
        /// <param name="brandName">brand_name.</param>
        /// <param name="locale">locale.</param>
        /// <param name="shippingPreference">shipping_preference.</param>
        /// <param name="contactPreference">contact_preference.</param>
        /// <param name="returnUrl">return_url.</param>
        /// <param name="cancelUrl">cancel_url.</param>
        /// <param name="appSwitchContext">app_switch_context.</param>
        /// <param name="landingPage">landing_page.</param>
        /// <param name="userAction">user_action.</param>
        /// <param name="paymentMethodPreference">payment_method_preference.</param>
        /// <param name="orderUpdateCallbackConfig">order_update_callback_config.</param>
        public PaypalWalletExperienceContext(
            string brandName = null,
            string locale = null,
            Models.PaypalWalletContextShippingPreference? shippingPreference = Models.PaypalWalletContextShippingPreference.GetFromFile,
            Models.PaypalWalletContactPreference? contactPreference = Models.PaypalWalletContactPreference.NoContactInfo,
            string returnUrl = null,
            string cancelUrl = null,
            Models.AppSwitchContext appSwitchContext = null,
            Models.PaypalExperienceLandingPage? landingPage = Models.PaypalExperienceLandingPage.NoPreference,
            Models.PaypalExperienceUserAction? userAction = Models.PaypalExperienceUserAction.Continue,
            Models.PayeePaymentMethodPreference? paymentMethodPreference = Models.PayeePaymentMethodPreference.Unrestricted,
            Models.CallbackConfiguration orderUpdateCallbackConfig = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.BrandName = brandName;
            this.Locale = locale;
            this.ShippingPreference = shippingPreference;
            this.ContactPreference = contactPreference;
            this.ReturnUrl = returnUrl;
            this.CancelUrl = cancelUrl;
            this.AppSwitchContext = appSwitchContext;
            this.LandingPage = landingPage;
            this.UserAction = userAction;
            this.PaymentMethodPreference = paymentMethodPreference;
            this.OrderUpdateCallbackConfig = orderUpdateCallbackConfig;
        }

        /// <summary>
        /// The label that overrides the business name in the PayPal account on the PayPal site. The pattern is defined by an external party and supports Unicode.
        /// </summary>
        [JsonProperty("brand_name", NullValueHandling = NullValueHandling.Ignore)]
        public string BrandName { get; set; }

        /// <summary>
        /// The [language tag](https://tools.ietf.org/html/bcp47#section-2) for the language in which to localize the error-related strings, such as messages, issues, and suggested actions. The tag is made up of the [ISO 639-2 language code](https://www.loc.gov/standards/iso639-2/php/code_list.php), the optional [ISO-15924 script tag](https://www.unicode.org/iso15924/codelists.html), and the [ISO-3166 alpha-2 country code](/api/rest/reference/country-codes/) or [M49 region code](https://unstats.un.org/unsd/methodology/m49/).
        /// </summary>
        [JsonProperty("locale", NullValueHandling = NullValueHandling.Ignore)]
        public string Locale { get; set; }

        /// <summary>
        /// The location from which the shipping address is derived.
        /// </summary>
        [JsonProperty("shipping_preference", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PaypalWalletContextShippingPreference? ShippingPreference { get; set; }

        /// <summary>
        /// <![CDATA[
        /// The preference to display the contact information (buyer’s shipping email & phone number) on PayPal's checkout for easy merchant-buyer communication.
        /// ]]>
        /// </summary>
        [JsonProperty("contact_preference", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PaypalWalletContactPreference? ContactPreference { get; set; }

        /// <summary>
        /// Describes the URL.
        /// </summary>
        [JsonProperty("return_url", NullValueHandling = NullValueHandling.Ignore)]
        public string ReturnUrl { get; set; }

        /// <summary>
        /// Describes the URL.
        /// </summary>
        [JsonProperty("cancel_url", NullValueHandling = NullValueHandling.Ignore)]
        public string CancelUrl { get; set; }

        /// <summary>
        /// Merchant provided details of the native app or mobile web browser to facilitate buyer's app switch to the PayPal consumer app.
        /// </summary>
        [JsonProperty("app_switch_context", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AppSwitchContext AppSwitchContext { get; set; }

        /// <summary>
        /// The type of landing page to show on the PayPal site for customer checkout.
        /// </summary>
        [JsonProperty("landing_page", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PaypalExperienceLandingPage? LandingPage { get; set; }

        /// <summary>
        /// Configures a Continue or Pay Now checkout flow.
        /// </summary>
        [JsonProperty("user_action", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PaypalExperienceUserAction? UserAction { get; set; }

        /// <summary>
        /// The merchant-preferred payment methods.
        /// </summary>
        [JsonProperty("payment_method_preference", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PayeePaymentMethodPreference? PaymentMethodPreference { get; set; }

        /// <summary>
        /// CallBack Configuration that the merchant can provide to PayPal/Venmo.
        /// </summary>
        [JsonProperty("order_update_callback_config", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CallbackConfiguration OrderUpdateCallbackConfig { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaypalWalletExperienceContext : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"BrandName = {this.BrandName ?? "null"}");
            toStringOutput.Add($"Locale = {this.Locale ?? "null"}");
            toStringOutput.Add($"ShippingPreference = {(this.ShippingPreference == null ? "null" : this.ShippingPreference.ToString())}");
            toStringOutput.Add($"ContactPreference = {(this.ContactPreference == null ? "null" : this.ContactPreference.ToString())}");
            toStringOutput.Add($"ReturnUrl = {this.ReturnUrl ?? "null"}");
            toStringOutput.Add($"CancelUrl = {this.CancelUrl ?? "null"}");
            toStringOutput.Add($"AppSwitchContext = {(this.AppSwitchContext == null ? "null" : this.AppSwitchContext.ToString())}");
            toStringOutput.Add($"LandingPage = {(this.LandingPage == null ? "null" : this.LandingPage.ToString())}");
            toStringOutput.Add($"UserAction = {(this.UserAction == null ? "null" : this.UserAction.ToString())}");
            toStringOutput.Add($"PaymentMethodPreference = {(this.PaymentMethodPreference == null ? "null" : this.PaymentMethodPreference.ToString())}");
            toStringOutput.Add($"OrderUpdateCallbackConfig = {(this.OrderUpdateCallbackConfig == null ? "null" : this.OrderUpdateCallbackConfig.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}