// <copyright file="PaypalWalletStoredCredential.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// PaypalWalletStoredCredential.
    /// </summary>
    public class PaypalWalletStoredCredential
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaypalWalletStoredCredential"/> class.
        /// </summary>
        public PaypalWalletStoredCredential()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PaypalWalletStoredCredential"/> class.
        /// </summary>
        /// <param name="paymentInitiator">payment_initiator.</param>
        /// <param name="chargePattern">charge_pattern.</param>
        /// <param name="usagePattern">usage_pattern.</param>
        /// <param name="usage">usage.</param>
        public PaypalWalletStoredCredential(
            Models.PaymentInitiator paymentInitiator,
            Models.UsagePattern? chargePattern = null,
            Models.UsagePattern? usagePattern = null,
            Models.StoredPaymentSourceUsageType? usage = Models.StoredPaymentSourceUsageType.Derived)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.PaymentInitiator = paymentInitiator;
            this.ChargePattern = chargePattern;
            this.UsagePattern = usagePattern;
            this.Usage = usage;
        }

        /// <summary>
        /// The person or party who initiated or triggered the payment.
        /// </summary>
        [JsonProperty("payment_initiator")]
        public Models.PaymentInitiator PaymentInitiator { get; set; }

        /// <summary>
        /// DEPRECATED. Expected business/pricing model for the billing agreement, Please use usage_pattern instead.
        /// </summary>
        [JsonProperty("charge_pattern", NullValueHandling = NullValueHandling.Ignore)]
        public Models.UsagePattern? ChargePattern { get; set; }

        /// <summary>
        /// Expected business/pricing model for the billing agreement.
        /// </summary>
        [JsonProperty("usage_pattern", NullValueHandling = NullValueHandling.Ignore)]
        public Models.UsagePattern? UsagePattern { get; set; }

        /// <summary>
        /// Indicates if this is a `first` or `subsequent` payment using a stored payment source (also referred to as stored credential or card on file).
        /// </summary>
        [JsonProperty("usage", NullValueHandling = NullValueHandling.Ignore)]
        public Models.StoredPaymentSourceUsageType? Usage { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"PaypalWalletStoredCredential : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"PaymentInitiator = {this.PaymentInitiator}");
            toStringOutput.Add($"ChargePattern = {(this.ChargePattern == null ? "null" : this.ChargePattern.ToString())}");
            toStringOutput.Add($"UsagePattern = {(this.UsagePattern == null ? "null" : this.UsagePattern.ToString())}");
            toStringOutput.Add($"Usage = {(this.Usage == null ? "null" : this.Usage.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}