// <copyright file="SellerPayableBreakdown.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SellerPayableBreakdown.
    /// </summary>
    public class SellerPayableBreakdown
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SellerPayableBreakdown"/> class.
        /// </summary>
        public SellerPayableBreakdown()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SellerPayableBreakdown"/> class.
        /// </summary>
        /// <param name="grossAmount">gross_amount.</param>
        /// <param name="paypalFee">paypal_fee.</param>
        /// <param name="paypalFeeInReceivableCurrency">paypal_fee_in_receivable_currency.</param>
        /// <param name="netAmount">net_amount.</param>
        /// <param name="netAmountInReceivableCurrency">net_amount_in_receivable_currency.</param>
        /// <param name="platformFees">platform_fees.</param>
        /// <param name="netAmountBreakdown">net_amount_breakdown.</param>
        /// <param name="totalRefundedAmount">total_refunded_amount.</param>
        public SellerPayableBreakdown(
            Models.Money grossAmount = null,
            Models.Money paypalFee = null,
            Models.Money paypalFeeInReceivableCurrency = null,
            Models.Money netAmount = null,
            Models.Money netAmountInReceivableCurrency = null,
            List<Models.PlatformFee> platformFees = null,
            List<Models.NetAmountBreakdownItem> netAmountBreakdown = null,
            Models.Money totalRefundedAmount = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.GrossAmount = grossAmount;
            this.PaypalFee = paypalFee;
            this.PaypalFeeInReceivableCurrency = paypalFeeInReceivableCurrency;
            this.NetAmount = netAmount;
            this.NetAmountInReceivableCurrency = netAmountInReceivableCurrency;
            this.PlatformFees = platformFees;
            this.NetAmountBreakdown = netAmountBreakdown;
            this.TotalRefundedAmount = totalRefundedAmount;
        }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("gross_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money GrossAmount { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("paypal_fee", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money PaypalFee { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("paypal_fee_in_receivable_currency", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money PaypalFeeInReceivableCurrency { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("net_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money NetAmount { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("net_amount_in_receivable_currency", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money NetAmountInReceivableCurrency { get; set; }

        /// <summary>
        /// An array of platform or partner fees, commissions, or brokerage fees for the refund.
        /// </summary>
        [JsonProperty("platform_fees", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.PlatformFee> PlatformFees { get; set; }

        /// <summary>
        /// An array of breakdown values for the net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the payee holds their funds.
        /// </summary>
        [JsonProperty("net_amount_breakdown", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.NetAmountBreakdownItem> NetAmountBreakdown { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("total_refunded_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money TotalRefundedAmount { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SellerPayableBreakdown : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"GrossAmount = {(this.GrossAmount == null ? "null" : this.GrossAmount.ToString())}");
            toStringOutput.Add($"PaypalFee = {(this.PaypalFee == null ? "null" : this.PaypalFee.ToString())}");
            toStringOutput.Add($"PaypalFeeInReceivableCurrency = {(this.PaypalFeeInReceivableCurrency == null ? "null" : this.PaypalFeeInReceivableCurrency.ToString())}");
            toStringOutput.Add($"NetAmount = {(this.NetAmount == null ? "null" : this.NetAmount.ToString())}");
            toStringOutput.Add($"NetAmountInReceivableCurrency = {(this.NetAmountInReceivableCurrency == null ? "null" : this.NetAmountInReceivableCurrency.ToString())}");
            toStringOutput.Add($"PlatformFees = {(this.PlatformFees == null ? "null" : $"[{string.Join(", ", this.PlatformFees)} ]")}");
            toStringOutput.Add($"NetAmountBreakdown = {(this.NetAmountBreakdown == null ? "null" : $"[{string.Join(", ", this.NetAmountBreakdown)} ]")}");
            toStringOutput.Add($"TotalRefundedAmount = {(this.TotalRefundedAmount == null ? "null" : this.TotalRefundedAmount.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}