// <copyright file="SellerReceivableBreakdown.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SellerReceivableBreakdown.
    /// </summary>
    public class SellerReceivableBreakdown
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SellerReceivableBreakdown"/> class.
        /// </summary>
        public SellerReceivableBreakdown()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SellerReceivableBreakdown"/> class.
        /// </summary>
        /// <param name="grossAmount">gross_amount.</param>
        /// <param name="paypalFee">paypal_fee.</param>
        /// <param name="paypalFeeInReceivableCurrency">paypal_fee_in_receivable_currency.</param>
        /// <param name="netAmount">net_amount.</param>
        /// <param name="receivableAmount">receivable_amount.</param>
        /// <param name="exchangeRate">exchange_rate.</param>
        /// <param name="platformFees">platform_fees.</param>
        public SellerReceivableBreakdown(
            Models.Money grossAmount,
            Models.Money paypalFee = null,
            Models.Money paypalFeeInReceivableCurrency = null,
            Models.Money netAmount = null,
            Models.Money receivableAmount = null,
            Models.ExchangeRate exchangeRate = null,
            List<Models.PlatformFee> platformFees = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.GrossAmount = grossAmount;
            this.PaypalFee = paypalFee;
            this.PaypalFeeInReceivableCurrency = paypalFeeInReceivableCurrency;
            this.NetAmount = netAmount;
            this.ReceivableAmount = receivableAmount;
            this.ExchangeRate = exchangeRate;
            this.PlatformFees = platformFees;
        }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("gross_amount")]
        public Models.Money GrossAmount { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("paypal_fee", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money PaypalFee { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("paypal_fee_in_receivable_currency", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money PaypalFeeInReceivableCurrency { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("net_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money NetAmount { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("receivable_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money ReceivableAmount { get; set; }

        /// <summary>
        /// The exchange rate that determines the amount to convert from one currency to another currency.
        /// </summary>
        [JsonProperty("exchange_rate", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ExchangeRate ExchangeRate { get; set; }

        /// <summary>
        /// An array of platform or partner fees, commissions, or brokerage fees that associated with the captured payment.
        /// </summary>
        [JsonProperty("platform_fees", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.PlatformFee> PlatformFees { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SellerReceivableBreakdown : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"GrossAmount = {(this.GrossAmount == null ? "null" : this.GrossAmount.ToString())}");
            toStringOutput.Add($"PaypalFee = {(this.PaypalFee == null ? "null" : this.PaypalFee.ToString())}");
            toStringOutput.Add($"PaypalFeeInReceivableCurrency = {(this.PaypalFeeInReceivableCurrency == null ? "null" : this.PaypalFeeInReceivableCurrency.ToString())}");
            toStringOutput.Add($"NetAmount = {(this.NetAmount == null ? "null" : this.NetAmount.ToString())}");
            toStringOutput.Add($"ReceivableAmount = {(this.ReceivableAmount == null ? "null" : this.ReceivableAmount.ToString())}");
            toStringOutput.Add($"ExchangeRate = {(this.ExchangeRate == null ? "null" : this.ExchangeRate.ToString())}");
            toStringOutput.Add($"PlatformFees = {(this.PlatformFees == null ? "null" : $"[{string.Join(", ", this.PlatformFees)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}