// <copyright file="SubscriptionTransactionDetails.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// SubscriptionTransactionDetails.
    /// </summary>
    public class SubscriptionTransactionDetails
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionTransactionDetails"/> class.
        /// </summary>
        public SubscriptionTransactionDetails()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionTransactionDetails"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="amountWithBreakdown">amount_with_breakdown.</param>
        /// <param name="time">time.</param>
        /// <param name="status">status.</param>
        /// <param name="payerName">payer_name.</param>
        /// <param name="payerEmail">payer_email.</param>
        public SubscriptionTransactionDetails(
            string id,
            Models.SubscriptionAmountWithBreakdown amountWithBreakdown,
            string time,
            Models.CaptureStatus? status = null,
            Models.SubscriptionPayerName payerName = null,
            string payerEmail = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Status = status;
            this.Id = id;
            this.AmountWithBreakdown = amountWithBreakdown;
            this.PayerName = payerName;
            this.PayerEmail = payerEmail;
            this.Time = time;
        }

        /// <summary>
        /// The status of the captured payment.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.CaptureStatus? Status { get; set; }

        /// <summary>
        /// The PayPal-generated transaction ID.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// The breakdown details for the amount. Includes the gross, tax, fee, and shipping amounts.
        /// </summary>
        [JsonProperty("amount_with_breakdown")]
        public Models.SubscriptionAmountWithBreakdown AmountWithBreakdown { get; set; }

        /// <summary>
        /// The name of the party.
        /// </summary>
        [JsonProperty("payer_name", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SubscriptionPayerName PayerName { get; set; }

        /// <summary>
        /// The internationalized email address. Note: Up to 64 characters are allowed before and 255 characters are allowed after the @ sign. However, the generally accepted maximum length for an email address is 254 characters. The pattern verifies that an unquoted @ sign exists.
        /// </summary>
        [JsonProperty("payer_email", NullValueHandling = NullValueHandling.Ignore)]
        public string PayerEmail { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("time")]
        public string Time { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"SubscriptionTransactionDetails : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"AmountWithBreakdown = {(this.AmountWithBreakdown == null ? "null" : this.AmountWithBreakdown.ToString())}");
            toStringOutput.Add($"PayerName = {(this.PayerName == null ? "null" : this.PayerName.ToString())}");
            toStringOutput.Add($"PayerEmail = {this.PayerEmail ?? "null"}");
            toStringOutput.Add($"Time = {this.Time ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}