// <copyright file="Subscription.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// Subscription.
    /// </summary>
    public class Subscription
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Subscription"/> class.
        /// </summary>
        public Subscription()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Subscription"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="planId">plan_id.</param>
        /// <param name="startTime">start_time.</param>
        /// <param name="quantity">quantity.</param>
        /// <param name="shippingAmount">shipping_amount.</param>
        /// <param name="subscriber">subscriber.</param>
        /// <param name="billingInfo">billing_info.</param>
        /// <param name="createTime">create_time.</param>
        /// <param name="updateTime">update_time.</param>
        /// <param name="customId">custom_id.</param>
        /// <param name="planOverridden">plan_overridden.</param>
        /// <param name="plan">plan.</param>
        /// <param name="links">links.</param>
        public Subscription(
            string id = null,
            string planId = null,
            string startTime = null,
            string quantity = null,
            Models.Money shippingAmount = null,
            Models.Subscriber subscriber = null,
            Models.SubscriptionBillingInformation billingInfo = null,
            string createTime = null,
            string updateTime = null,
            string customId = null,
            bool? planOverridden = null,
            Models.PlanDetails plan = null,
            List<Models.LinkDescription> links = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.PlanId = planId;
            this.StartTime = startTime;
            this.Quantity = quantity;
            this.ShippingAmount = shippingAmount;
            this.Subscriber = subscriber;
            this.BillingInfo = billingInfo;
            this.CreateTime = createTime;
            this.UpdateTime = updateTime;
            this.CustomId = customId;
            this.PlanOverridden = planOverridden;
            this.Plan = plan;
            this.Links = links;
        }

        /// <summary>
        /// The PayPal-generated ID for the subscription.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// The ID of the plan.
        /// </summary>
        [JsonProperty("plan_id", NullValueHandling = NullValueHandling.Ignore)]
        public string PlanId { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("start_time", NullValueHandling = NullValueHandling.Ignore)]
        public string StartTime { get; set; }

        /// <summary>
        /// The quantity of the product in the subscription.
        /// </summary>
        [JsonProperty("quantity", NullValueHandling = NullValueHandling.Ignore)]
        public string Quantity { get; set; }

        /// <summary>
        /// The currency and amount for a financial transaction, such as a balance or payment due.
        /// </summary>
        [JsonProperty("shipping_amount", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Money ShippingAmount { get; set; }

        /// <summary>
        /// The subscriber response information.
        /// </summary>
        [JsonProperty("subscriber", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Subscriber Subscriber { get; set; }

        /// <summary>
        /// The billing details for the subscription. If the subscription was or is active, these fields are populated.
        /// </summary>
        [JsonProperty("billing_info", NullValueHandling = NullValueHandling.Ignore)]
        public Models.SubscriptionBillingInformation BillingInfo { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("create_time", NullValueHandling = NullValueHandling.Ignore)]
        public string CreateTime { get; set; }

        /// <summary>
        /// The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional. Note: The regular expression provides guidance but does not reject all invalid dates.
        /// </summary>
        [JsonProperty("update_time", NullValueHandling = NullValueHandling.Ignore)]
        public string UpdateTime { get; set; }

        /// <summary>
        /// The custom id for the subscription. Can be invoice id.
        /// </summary>
        [JsonProperty("custom_id", NullValueHandling = NullValueHandling.Ignore)]
        public string CustomId { get; set; }

        /// <summary>
        /// Indicates whether the subscription has overridden any plan attributes.
        /// </summary>
        [JsonProperty("plan_overridden", NullValueHandling = NullValueHandling.Ignore)]
        public bool? PlanOverridden { get; set; }

        /// <summary>
        /// The plan details.
        /// </summary>
        [JsonProperty("plan", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PlanDetails Plan { get; set; }

        /// <summary>
        /// An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
        /// </summary>
        [JsonProperty("links", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.LinkDescription> Links { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Subscription : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"PlanId = {this.PlanId ?? "null"}");
            toStringOutput.Add($"StartTime = {this.StartTime ?? "null"}");
            toStringOutput.Add($"Quantity = {this.Quantity ?? "null"}");
            toStringOutput.Add($"ShippingAmount = {(this.ShippingAmount == null ? "null" : this.ShippingAmount.ToString())}");
            toStringOutput.Add($"Subscriber = {(this.Subscriber == null ? "null" : this.Subscriber.ToString())}");
            toStringOutput.Add($"BillingInfo = {(this.BillingInfo == null ? "null" : this.BillingInfo.ToString())}");
            toStringOutput.Add($"CreateTime = {this.CreateTime ?? "null"}");
            toStringOutput.Add($"UpdateTime = {this.UpdateTime ?? "null"}");
            toStringOutput.Add($"CustomId = {this.CustomId ?? "null"}");
            toStringOutput.Add($"PlanOverridden = {(this.PlanOverridden == null ? "null" : this.PlanOverridden.ToString())}");
            toStringOutput.Add($"Plan = {(this.Plan == null ? "null" : this.Plan.ToString())}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : $"[{string.Join(", ", this.Links)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}