// <copyright file="ThreeDSecureCardAuthenticationResponse.cs" company="APIMatic">
// PaypalServerSdk.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PaypalServerSdk.Standard.Utilities;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace PaypalServerSdk.Standard.Models
{
    /// <summary>
    /// ThreeDSecureCardAuthenticationResponse.
    /// </summary>
    public class ThreeDSecureCardAuthenticationResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The JsonValue value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public JsonValue this[string key]
        {
            get => additionalProperties.GetValue<JsonValue>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDSecureCardAuthenticationResponse"/> class.
        /// </summary>
        public ThreeDSecureCardAuthenticationResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThreeDSecureCardAuthenticationResponse"/> class.
        /// </summary>
        /// <param name="authenticationStatus">authentication_status.</param>
        /// <param name="enrollmentStatus">enrollment_status.</param>
        /// <param name="authenticationId">authentication_id.</param>
        public ThreeDSecureCardAuthenticationResponse(
            Models.PaResStatus? authenticationStatus = null,
            Models.EnrollmentStatus? enrollmentStatus = null,
            string authenticationId = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.AuthenticationStatus = authenticationStatus;
            this.EnrollmentStatus = enrollmentStatus;
            this.AuthenticationId = authenticationId;
        }

        /// <summary>
        /// Transactions status result identifier. The outcome of the issuer's authentication.
        /// </summary>
        [JsonProperty("authentication_status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.PaResStatus? AuthenticationStatus { get; set; }

        /// <summary>
        /// Status of Authentication eligibility.
        /// </summary>
        [JsonProperty("enrollment_status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.EnrollmentStatus? EnrollmentStatus { get; set; }

        /// <summary>
        /// The externally received 3ds authentication id, to be returned in card detokenization response.
        /// </summary>
        [JsonProperty("authentication_id", NullValueHandling = NullValueHandling.Ignore)]
        public string AuthenticationId { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ThreeDSecureCardAuthenticationResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AuthenticationStatus = {(this.AuthenticationStatus == null ? "null" : this.AuthenticationStatus.ToString())}");
            toStringOutput.Add($"EnrollmentStatus = {(this.EnrollmentStatus == null ? "null" : this.EnrollmentStatus.ToString())}");
            toStringOutput.Add($"AuthenticationId = {this.AuthenticationId ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}